/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cr.ac.ucr.juegodeparchisc5c589.vista;

import cr.ac.ucr.juegodeparchisc5c589.controlador.ControladorJuego;

/**
 *
 * @author Thinkpad P52
 */
public class PanelControl extends javax.swing.JPanel {

    /**
     * Creates new form PanelControl
     */
    public PanelControl() {
        initComponents();
    }
    public void escuchar(ControladorJuego controlador){
        btnAtras.addActionListener(controlador);
        btnDado.addActionListener(controlador);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlFondo = new javax.swing.JLabel();
        btnDado = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 610, 500));

        btnDado.setText("Dado");
        add(btnDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        btnAtras.setText("Atras");
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new PanelControl().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnDado;
    private javax.swing.JLabel jlFondo;
    // End of variables declaration//GEN-END:variables
}
