/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cr.ac.ucr.juegodeparchisc5c589.vista;

import cr.ac.ucr.juegodeparchisc5c589.controlador.ControladorPrincipal;

/**
 *
 * @author Thinkpad P52
 */
public class GUIInstrucciones extends javax.swing.JFrame {
    
   

    /**
     * Creates new form GUIInstrucciones
     */
    public GUIInstrucciones(ControladorPrincipal controlador) {
        initComponents();
        escuchar(controlador);
    }
    
    public void escuchar(ControladorPrincipal controlador){
    btnAtras.addActionListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        jlFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Instrucciones:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 140, 50));

        btnAtras.setText("Atras");
        btnAtras.setActionCommand("AtrasInstrucciones");
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 110, 40));

        jlFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Thinkpad P52\\OneDrive - Universidad de Costa Rica\\Documentos\\segundo semestre\\Imagenes del Juego de parchis\\plantilla para colocar mensajes.jpg")); // NOI18N
        getContentPane().add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlFondo;
    // End of variables declaration//GEN-END:variables
}
